### PR TITLE
restore detection of wrongly coded header field names

### PR DESCRIPTION
**Pull request by albrechtd**
This patch restores the detection if wrongly coded header field _names_ which has been removed since commit edf84ba6.  See [RFC 6532 section 3](https://tools.ietf.org/html/rfc6532#section-3):

> Note that this protocol does not change rules in RFC 5322 for defining header field names.  The bodies of header fields are allowed to contain Unicode characters, but the header field names themselves must consist of ASCII characters only.

I.e. whilst using g_utf8_validate() for the body (value) is actually correct (I missed that, sorry), the name should be validated using the original method.

Side note: please excuse my use of “over-explicit” constructs (like unnecessary braces, explicit unsigned consts, etc.).  I usually write software for safety-related applications (IEC 61508 & friends), where this is mandatory.  See standards like [MISRA C:2012](https://www.misra.org.uk/Publications/tabid/57/Default.aspx#label-c3) or [SEI CERT C Coding Standard](https://www.securecoding.cert.org/confluence/display/c/SEI+CERT+C+Coding+Standard) for explanations why this is actually a good idea…

### CODE REVIEW

**Comment by jstedfast** [comment]
There's no need to do this because I'm pretty sure they are validated already as part of parsing - as soon as we get to a non-ascii character in a field name, we abort parsing headers.

Do you have an example where this isn't the case?

**Comment by albrechtd** [comment]
For the attached example, the broken “Häder:” at offset 699 is not detected unless this patch is applied.

I don't think it is a good idea to _abort_ parsing if such a header is detected.  It might actually be a method to evade security scanners as some MUA's might just ignore them, and happily execute the attached virus…  So I strongly recommend to just keep it!
[BADMAIL.zip](https://github.com/jstedfast/gmime/files/1459071/BADMAIL.zip)

**Comment by albrechtd** [comment]
> I don't think it is a good idea to abort parsing if such a header is detected.

Or, abort parsing in GMIME_RFC_COMPLIANCE_STRICT mode, but _not_ in GMIME_RFC_COMPLIANCE_LOOSE mode.

**Comment by jstedfast** [comment]
Thanks. I guess is_ctrl() doesn't match 8bit chars

**Pull request merged**
